// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcahrolojfosvknoxiho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjYWhyb2xvamZvc3Zrbm94aWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MDA2NDcsImV4cCI6MjA1MDk3NjY0N30.hBGs-MSG1eDjAZ_jh6L97DDpFAz8XLNmIIC8kDg4Lyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);